### ISSUE TITLE
list subcategories in category

### ISSUE THREAD

**Issue by jpanossi** [CSE187-Team2/.github#12]

**Comment by ArmandAgopian** [comment]
```
SELECT jsonb_build_object('id', c.id) || c.data || jsonb_build_object(
  'subcategories', jsonb_agg(jsonb_build_object(
    'id', s.id, 'name', s.data->'name')
  )) as data
FROM category c
LEFT JOIN subcategory s on c.id = s.category_id
GROUP BY c.id;
```

**Comment by ArmandAgopian** [comment]
Here's the code that grabs all the subcategories of each category nested, I ran into a problem where it was getting too complicated return the category AND subcategories on edits and deletes

**Comment by jpanossi** [comment]
Are you trying to join the category data with the subcategory list? Why not just return a list of subcategories itself
